title: Báo điện tử TH16
description: Đồ án giữa kỳ Web CQ2016-33
permalink: pretty
url: https://bao-dien-tu.beohoang98.now.sh

collections:
  pages:
    output: true
    permalink: /:slug/
  posts:
    output: true
    permalink: /:categories/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Beo

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

browserify:

  # target exts to convert
  exts: [".js"]

  # use installed 'browserify'
  command: "./node_modules/.bin/browserify -"

  # execute `npm install` on initialize if true
  npm_install: false

  # set nvm properties if you want to use with nvm installed automatically
  nvm:

    # required modules
    modules: []

    # browserify option string
    option: "--exclude node_modules/**/* -o main.js"

    # node version if you specify, or use '.nvmrc' if 'null'
    node_version: null