# this config copy from https://jekyllrb.com/docs/continuous-integration/circleci/

defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  deploy:
    <<: *defaults
    docker:
      - image: starefossen/ruby-node
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - run:
            name: Configure Bundler
            command: |
              echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
              source $BASH_ENV
              gem install bundler
      - add_ssh_keys:
          fingerprints:
            - "86:2d:80:37:20:2b:21:91:18:bc:61:dc:9f:14:21:22"
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git clone git@github.com:beohoang98/bao-dien-tu-th16-static.git ~/repo
      - attach_workspace:
          at: ~/repo
      - run:
          name: Check folder
          command: cd ~/repo && ls -al # for debug
      - restore_cache:
            keys:
              - rubygems-v2-{{ checksum "Gemfile" }}
              - rubygems-v2-fallback
      - restore_cache:
            keys:
              - node-v2-{{ checksum "package.json" }}
              - node-v2-fallback
      - run: bundle install --path $BUNDLE_PATH
      - run: npm install
      - save_cache:
          key: rubygems-v2-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: node-v2-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: bundle exec jekyll build
      - run:
          name: Deploy Github Pages
          command: |
            git config user.name 'Beo Hoang (CircleCI)'
            git config user.email 'beohoang98@noreply.users.github.com'
            npm run deploy
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
